application: guestbook-python-gae
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: guestbook.application

libraries:
- name: jinja2
  version: latest
